export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNOUT = 'SIGNOUT';
export const GET_FEEDBACK = 'GET_FEEDBACK';
export const GET_DASHBOARD = 'GET_DASHBOARD';
export const RESTORE_LOGINDATA = 'RESTORE_LOGINDATA';
